export enum SlotGameType {
  CLASSIC = 'CLASSIC',
  CASCADING = 'CASCADING',
  FALLING_WILDS = 'FALLING_WILDS',
  STICKY_WILDS = 'STICKY_WILDS',
  NUDGING_WILDS = 'NUDGING_WILDS',
  LINKING_WILDS = 'LINKING_WILDS',
  REPLICATING_REELS = 'REPLICATING_REELS',
  STACKED_SYMBOLS = 'STACKED_SYMBOLS',
  MULTIPLIERS = 'MULTIPLIERS',
  BONUS_FEATURE = 'BONUS_FEATURE',
  PROGRESSIVE_JACKPOT = 'PROGRESSIVE_JACKPOT',
  FIXED_JACKPOT = 'FIXED_JACKPOT',
}
